config/routes.rb
Rails.application.routes.draw do
  resource :registrations, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]
  resource :settings, only: [:edit, :update]

  resources :users, only: [:index, :show] do
    resource :follows, only: [:create, :destroy] 
    get :favorites, on: :member
    get :follows, on: :member
    get :followers, on: :member 
  end 

  resources :tweets do
    resource :favorites, only: [:create, :destroy]
    resource :doubts, only: [:create, :destroy]
    get :timeline, on: :collection
    get :low, on: :collection
    get :medium, on: :collection
    get :positive, on: :collection
  end 

  resources :notifications, only: [:index]
  
  root to: 'registrations#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :favorites, dependent: :destroy 

    has_many :notifications, dependent: :destroy
    has_many :doubts, dependent: :destroy

    validates :user, presence: true
	validates :content, presence: true, length: { in: 1..140}

    def favorited_by? user
        if user.instance_of?(User)
            favorites.where(user_id: user.id).exists?
        end
    end 

    def doubted_by? user
        if user.instance_of?(User)
            doubts.where(user_id: user.id).exists?
        end
    end 

    def get_sentiment
        require 'net/http'
        require 'uri'
        require 'json'

        text = self.content

        api = ENV['API_KEY']

        uri = URI.parse("https://language.googleapis.com/v1beta2/documents:analyzeSentiment?key=#{api}")
        request = Net::HTTP::Post.new(uri)
        request.content_type = "application/json"
        request.body = ""
        request.body = {
            document:{
                type:'PLAIN_TEXT',
                content: text
            },
            encodingType: 'UTF8'
        }.to_json

        req_options = {
            use_ssl: uri.scheme == "https",
        }
      
        response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
          http.request(request)
        end
      
        json = JSON.parse(response.body)
        score =  json['documentSentiment']['score']

        self.score = score
        self.save
    end

    def add_score user
        user.score_sum += self.score
        if user.tweets.count > 0
            user.score_ave = user.score_sum / user.tweets.count
        end
        user.save
    end

    def create_notification_like!(current_user)
        # すでに「いいね」されているか検索
        temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
        # いいねされていない場合のみ、通知レコードを作成
        if temp.blank?
            notification = current_user.active_notifications.new(
                post_id: id,
                visited_id: user_id,
                action: 'like'
            )
            # 自分の投稿に対するいいねの場合は、通知済みとする
            if notification.visitor_id == notification.visited_id
                notification.checked = true
            end
            notification.save if notification.valid?
        end
    end

    default_scope -> { order(created_at: :desc) }
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :require_login, except: [:index]
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    #@tweets = Tweet.all
    @tweets = Tweet.page(params[:page]).per(12)
    @tweet  = Tweet.new
    @notifications = current_user.passive_notifications.page(params[:page]).per(3)
    @notifications.where(checked: false).each do |notification|
      notification.update(checked: true)
    end
  end

  def timeline
    @tweets = Tweet.eager_load(user: :inverse_follows).where(follows: { follower_id: current_user.id }).page(params[:page]).per(12)
    @tweet  = Tweet.new
    @notifications = current_user.passive_notifications.page(params[:page]).per(3)
    @notifications.where(checked: false).each do |notification|
      notification.update(checked: true)
    end
  end

  def positive
    @tweets = Tweet.all.where("score > 0.3").page(params[:page]).per(12)
    @tweet  = Tweet.new
    @notifications = current_user.passive_notifications.page(params[:page]).per(3)
    @notifications.where(checked: false).each do |notification|
      notification.update(checked: true)
    end
  end

  def medium
    @tweets = Tweet.all.where("score >= 0").page(params[:page]).per(12)
    @tweet  = Tweet.new
    @notifications = current_user.passive_notifications.page(params[:page]).per(3)
    @notifications.where(checked: false).each do |notification|
      notification.update(checked: true)
    end
  end

  def low
    @tweets = Tweet.all.where("score > -0.5").page(params[:page]).per(12)
    @tweet  = Tweet.new
    @notifications = current_user.passive_notifications.page(params[:page]).per(3)
    @notifications.where(checked: false).each do |notification|
      notification.update(checked: true)
    end
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user
    

    respond_to do |format|
      if @tweet.save
        @tweet.get_sentiment
        @tweet.add_score(@tweet.user)
        format.html { redirect_to tweets_url, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
        @notifications = current_user.passive_notifications.page(params[:page]).per(3)
        @notifications.where(checked: false).each do |notification|
          notification.update(checked: true)
        end
      else
        @tweets = Tweet.all
        format.html { render :index }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
        @notifications = current_user.passive_notifications.page(params[:page]).per(3)
        @notifications.where(checked: false).each do |notification|
          notification.update(checked: true)
        end
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:content)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper

    def get_color(score)
        
        if score > 0.3
            return "background-color: #F0FFF0"
        elsif score >= 0
            return "background-color: #FFFFFF"
        elsif score > -0.5
            return "background-color: #FFFACD"
        else
            return "background-color: #FFE4E1"
        end
    end
end

app/views/tweets/_form.html.haml
= form_for @tweet do |f|
  - if @tweet.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tweet.errors.count, "error")} prohibited this tweet from being saved:"
      %ul
        - @tweet.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :content
    = f.text_field :content
  .actions
    = f.submit 'Save'

app/views/tweets/_panel.html.haml
- if logged_in?
  .panel.panel-default
    .panel-body
      = link_to user_path(current_user), class: "user" do
        %span.user-name
          = render_user_screen_name current_user
          - sum = current_user.score_sum
          - num = current_user.tweets.count
          - if num >= 10
            - if sum.to_f / num.to_f >= 0.3
              %i.fas.fa-award
        %span.user-id
          @#{current_user.name}
      .user-activity
        .row
          .col-xs-4.tweets-num
            .text
              つぶやき
            .num
              = link_to current_user.tweets.count, user_path(current_user)
          .col-xs-4.follow-num
            .text
              フォロー
            .num
              = link_to current_user.inverse_followers.count, follows_user_path(current_user)
          .col-xs-4.follower-num
            .text
              フォロワー
            .num
              = link_to current_user.followers.count, followers_user_path(current_user)
      - @tweet.errors.full_messages.each do |message|
        .alert.alert-danger= message
      = form_for @tweet do |f|
        .form-group
          = f.text_area :content, class: "form-control"
        = f.submit "つぶやく", class: "btn btn-info"
  
  .panel.panel-default
    .list-group
      .list-group-item
        = link_to notifications_path, class: "btn btn-info btn-block" do
          %i.far.fa-bell
      .list-group-item
        = render partial: "notifications/panel"

app/views/tweets/edit.html.haml
%h1 Editing tweet

= render 'form'

= link_to 'Show', @tweet
\|
= link_to 'Back', tweets_path

app/views/tweets/index.html.haml
#tweets-content
  .container
    .row
      .col-xs-4.left-content
        = render partial: "panel"
      .col-xs-8.right-content
        - if notice
          .alert.alert-info= notice
        .list-group
          .list-group-item
            .btn-group
              = link_to "すべてのつぶやき", tweets_path, class: "active btn btn-primary"
              = link_to "low", low_tweets_path, class: "active btn btn-danger"
              = link_to "medium", medium_tweets_path, class: "active btn btn-warning"
              = link_to "positive", positive_tweets_path, class: "btn btn-success"
              = link_to "フォローしている人のつぶやき", timeline_tweets_path, class: "btn btn-default"
          = render partial: "users/tweet", collection: @tweets

app/views/tweets/low.html.haml
#tweets-content
  .container
    .row
      .col-xs-4.left-content
        = render partial: "panel"
      .col-xs-8.right-content
        - if notice
          .alert.alert-info= notice
        .list-group
          .list-group-item
            .btn-group
              = link_to "すべてのつぶやき", tweets_path, class: "btn btn-default"
              = link_to "low", low_tweets_path, class: "active btn btn-primary"
              = link_to "medium", medium_tweets_path, class: "active btn btn-warning"
              = link_to "positive", positive_tweets_path, class: "active btn btn-success"
              = link_to "フォローしている人のつぶやき", timeline_tweets_path, class: "btn btn-default"
          = render partial: "users/tweet", collection: @tweets

app/views/tweets/medium.html.haml
#tweets-content
  .container
    .row
      .col-xs-4.left-content
        = render partial: "panel"
      .col-xs-8.right-content
        - if notice
          .alert.alert-info= notice
        .list-group
          .list-group-item
            .btn-group
              = link_to "すべてのつぶやき", tweets_path, class: "btn btn-default"
              = link_to "low", low_tweets_path, class: "active btn btn-danger"
              = link_to "medium", medium_tweets_path, class: "active btn btn-primary"
              = link_to "positive", positive_tweets_path, class: "active btn btn-success"
              = link_to "フォローしている人のつぶやき", timeline_tweets_path, class: "btn btn-default"
          = render partial: "users/tweet", collection: @tweets

app/views/tweets/new.html.haml
%h1 New tweet

= render 'form'

= link_to 'Back', tweets_path

app/views/tweets/positive.html.haml
#tweets-content
  .container
    .row
      .col-xs-4.left-content
        = render partial: "panel"
      .col-xs-8.right-content
        - if notice
          .alert.alert-info= notice
        .list-group
          .list-group-item
            .btn-group
              = link_to "すべてのつぶやき", tweets_path, class: "btn btn-default"
              = link_to "low", low_tweets_path, class: "active btn btn-danger"
              = link_to "medium", medium_tweets_path, class: "active btn btn-warning"
              = link_to "positive", positive_tweets_path, class: "active btn btn-primary"
              = link_to "フォローしている人のつぶやき", timeline_tweets_path, class: "btn btn-default" 
          = render partial: "users/tweet", collection: @tweets

app/views/tweets/show.html.haml
%p#notice= notice

%p
  %b User:
  = @tweet.user_id
%p
  %b Content:
  = @tweet.content

= link_to 'Edit', edit_tweet_path(@tweet)
\|
= link_to 'Back', tweets_path

app/views/tweets/timeline.html.haml
#tweets-content
  .container
    .row
      .col-xs-4.left-content
        = render partial: "panel"
      .col-xs-8.right-content
        - if notice
          .alert.alert-info= notice
        .list-group
          .list-group-item
            .btn-group
              = link_to "すべてのつぶやき", tweets_path, class: "btn btn-default"
              = link_to "low", low_tweets_path, class: "active btn btn-danger"
              = link_to "medium", medium_tweets_path, class: "active btn btn-warning"
              = link_to "positive", positive_tweets_path, class: "btn btn-success"
              = link_to "フォローしている人のつぶやき", timeline_tweets_path, class: "active btn btn-primary"
          = render partial: "users/tweet", collection: @tweets