config/routes.rb
Rails.application.routes.draw do
  resource :registrations, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]
  resource :settings, only: [:edit, :update]

  resources :users, only: [:index, :show] do
    resource :follows, only: [:create, :destroy] 
    get :favorites, on: :member
    get :follows, on: :member
    get :followers, on: :member 
  end 

  resources :tweets do
    resource :favorites, only: [:create, :destroy]
    resource :doubts, only: [:create, :destroy]
    get :timeline, on: :collection
    get :low, on: :collection
    get :medium, on: :collection
    get :positive, on: :collection
  end 

  resources :notifications, only: [:index]
  
  root to: 'registrations#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :tweets, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :follows, foreign_key: :follower_id
  has_many :inverse_followers, through: :follows
  has_many :inverse_follows, foreign_key: :inverse_follower_id, class_name: 'Follow'
  has_many :followers, through: :inverse_follows
  
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  has_many :doubts, dependent: :destroy
  
  validates :name, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A[a-z][a-z0-9]+\z/ }, length: { in: 4..24 }
  validates :screen_name, length: { maximum: 140 }
  validates :bio, length: { maximum: 200  }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password, confirmation: true, length: { in: 6..24 }, if: :password
  validates :password_confirmation, presence: true, if: :password

  default_scope -> { order(score_ave: :desc) }

  def followed_by? user
    if user.instance_of?(User)
      inverse_follows.where(follower_id: user.id).exists?
    end
  end 

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
        notification = current_user.active_notifications.new(
            visited_id: id,
            action: 'follow'
        )
        notification.save if notification.valid?
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :set_user, only: %i[ show edit update destroy ]
  
  before_action :require_login
  
  # GET /users or /users.json
  def index
    #@users = User.page(params[:page]).per(5)
    @users = User.all.page(params[:page]).per(5)
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets.page(params[:page]).per(5)
  end

  def favorites
    @user = User.find(params[:id])
    @favorites = @user.favorites.page(params[:page]).per(5)
  end
  
  def follows
    @user = User.find(params[:id])
    @follows = @user.inverse_followers.page(params[:page]).per(5)
  end

  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page]).per(5)
  end 
end

app/helpers/users_helper.rb
module UsersHelper
    def render_user_screen_name user
        if user.screen_name.blank?
            user.name
        else
            user.screen_name
        end
    end
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/users/_header.html.haml
.user-info
  - if notice
    .alert.alert-info= notice
  %span.user-name
    = render_user_screen_name(@user)
    - sum = @user.score_sum
    - num = @user.tweets.count
    - if num >= 10
      - if sum.to_f / num.to_f >= 0.3
        %i.fas.fa-award
  %span.user-id
    @#{@user.name}
  .bio
    = @user.bio

%ul.nav.nav-tabs.nav-justified
  %li{ class: action_name == "show" ? "active" : nil }
    = link_to user_path(@user) do
      .text
        つぶやき
      .num
        #{@user.tweets.count}
  %li{ class: action_name == "follows" ? "active" : nil }
    = link_to follows_user_path(@user) do
      .text
        フォロー
      .num
        #{@user.inverse_followers.count}
  %li{ class: action_name == "followers" ? "active" : nil }
    = link_to followers_user_path(@user) do
      .text
        フォロワー
      .num
        #{@user.followers.count}
  %li{ class: action_name == "favorites" ? "active" : nil }
    = link_to favorites_user_path(@user) do
      .text
        お気に入り
      .num
        #{@user.favorites.count}

app/views/users/_tweet.html.haml
= div_for tweet, style: get_color(tweet.score), class: "list-group-item" do |t|
  %h4.user
    %span.user-name
      - if t.user.screen_name.present?
        = link_to t.user.screen_name, user_path(t.user)
      - else
        = link_to t.user.name, user_path(t.user)
      - sum = t.user.score_sum
      - num = t.user.tweets.count
      - if num >= 10
        - if sum.to_f / num.to_f >= 0.3
          %i.fas.fa-award
    %span.user-id
      @#{t.user.name}

    %span.time.pull-right
      = distance_of_time_in_words_to_now(t.created_at)
    
    .clear
  .tweet-content
    %p
      = t.content
    .content-footer
      - if t.user.id != current_user.id
        - if t.user.followed_by? current_user
          = link_to user_follows_path(t.user), method: :delete do
            %i.fas.fa-handshake
        - else
          = link_to user_follows_path(t.user), method: :post do
            %i.far.fa-handshake

      - if t.favorited_by? current_user
        = link_to tweet_favorites_path(t), :method => :delete do
          %i.fas.fa-kiss-wink-heart
      - else
        = link_to tweet_favorites_path(t), :method => :post do
          %i.far.fa-kiss-wink-heart
      
      #{t.favorites.count}

      - if t.doubted_by? current_user
        = link_to tweet_doubts_path(t), method: :delete do
          %i.fas.fa-frown
      - else
        = link_to tweet_doubts_path(t), method: :post do
          %i.far.fa-frown

      #{t.doubts.count}

app/views/users/_user.html.haml
= div_for user, class: "list-group-item" do |u|
  %h4.user
    %span.user-name
      - if u.screen_name.present?
        = link_to u.screen_name, user_path(u)
      - else
        = link_to u.name, user_path(u)
      - sum = u.score_sum
      - num = u.tweets.count
      - if num >= 10
        - if sum.to_f / num.to_f >= 0.3
          %i.fas.fa-award
    %span.user-id
      @#{u.name}
  .bio
    = u.bio
  .follow-unfollow
    - if u.id != current_user.id
      - if u.followed_by? current_user
        = link_to user_follows_path(u), method: :delete do
          %i.fas.fa-handshake
      - else
        = link_to user_follows_path(u), method: :post do
          %i.far.fa-handshake

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/favorites.html.haml
.col-xs-8#users-content
  = render partial: "users/header"
  .list-group
    - if @user.favorites.empty?
      .list-group-item
        まだお気に入りに登録されたツイートはありません
    = render partial: "users/tweet", collection: @favorites.map{|f| f.tweet }
    = paginate(@favorites)

app/views/users/followers.html.haml
.col-xs-8#users-content
   = render partial: "users/header"
   .list-group
      = render @followers
      = paginate(@followers)

app/views/users/follows.html.haml
.col-xs-8#users-content
  = render partial: "users/header"
  .list-group
    = render @follows
    = paginate(@follows)

app/views/users/index.html.haml
.col-xs-8#users-content
  .list-group
    .list-group-item.user-list
      %h2 ランキング
    = render partial: "users/user", collection: @users
    = paginate(@users)

    

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
.col-xs-8#users-content
  = render partial: "users/header"
  .list-group
    - if @user.tweets.empty?
      .list-group-item
        まだツイートはありません
    = render partial: "users/tweet", collection: @tweets
    = paginate(@tweets)